import pygame

# screen
SCREEN_HEIGHT = 500
SCREEN_WIDTH = 500

# board
BOARD_SIZE = SCREEN_WIDTH * 0.7 if SCREEN_HEIGHT > SCREEN_WIDTH else SCREEN_HEIGHT * 0.7
BOARD_SIZE_TUPLE = (BOARD_SIZE, BOARD_SIZE)
BOARD_ZERO_X = (SCREEN_WIDTH - BOARD_SIZE) / 2
BOARD_ZERO_Y = (SCREEN_HEIGHT - BOARD_SIZE) / 2
BOARD_ZERO_POINT = (BOARD_ZERO_X, BOARD_ZERO_Y)
NUMBER_OF_SQUARES_IN_ROW = 3

# square
SQUARE_BORDER_WIDTH = 15
SQUARE_SIZE = (BOARD_SIZE - SQUARE_BORDER_WIDTH * (NUMBER_OF_SQUARES_IN_ROW + 1)) / NUMBER_OF_SQUARES_IN_ROW
SQUARE_OVAERALL_SIZE = SQUARE_SIZE + SQUARE_BORDER_WIDTH
SQUARE_SIZE_TUPLE = (SQUARE_SIZE, SQUARE_SIZE)

# sprites
SPRITE_SIZE = SQUARE_SIZE * 0.7
DOUGHNUT_SPRITE = pygame.image.load('assets/doughnut.jpg')
CROSS_SPRITE = pygame.image.load('assets/cross.jpg')
SPRITES = [DOUGHNUT_SPRITE, CROSS_SPRITE]
